window.AIRPORT_RANKING=[
{name:'闪电鼠',tag:'综合首选',logo:'assets/airports/shandianshu.jpg',url:'https://chenpin.shandianshuaff.com/#/?code=m28TvPVX',price:'￥15.40/月',traffic:'120GB',device:'不限设备 · 1×倍率',verified:true,summary:'套餐跨度完整，兼顾入门、多设备和较高流量需求。'},
{name:'大佬云',tag:'档位丰富',logo:'assets/airports/dalaoyun.png',url:'https://chenpin01.dalaoyunaff.com/#/?code=GQ6CL6Km',price:'￥16.10/月',traffic:'130GB',device:'不限设备',verified:true,summary:'月付、年付和一次性流量包并存，购买周期较灵活。'},
{name:'环球梯',tag:'流量灵活',logo:'assets/airports/huanqiuti.jpg',url:'https://chenpingan01.huanqiutiaff.com/#/?code=FGCcYdFo',price:'￥15.40/月',traffic:'120GB',device:'截图标注 3 线路',verified:true,summary:'月付与一次性流量包并存，适合常用和备用需求。'},
{name:'榴莲云',tag:'大流量',logo:'assets/airports/liulianyun.png',url:'https://chenpingan.liulianyunaff.com/#/?code=7pdjs9zt',price:'￥16.80/月',traffic:'140GB',device:'不限设备',verified:true,summary:'入门流量较充足，覆盖影音、下载和家庭多设备场景。'},
{name:'云界线',tag:'结构清晰',logo:'assets/airports/yunjiexian.png',url:'https://chenpingan.yunjiexianaff.com/#/?code=xLJGaIHM',price:'￥15.40/月',traffic:'150GB',device:'不限设备',verified:true,summary:'三档流量结构清楚，方便按使用量选择。'},
{name:'神行加速',tag:'均衡备选',logo:'assets/airports/shenxing.png',url:'https://chenpingan01.shenxingaff.com/#/?code=RZ48f9wP',price:'￥16.10/月',traffic:'120GB',device:'截图标注不限设备',verified:true,summary:'套餐从基础到高流量覆盖，档位分布直观。'},
{name:'二猫云',tag:'推荐选择',logo:'assets/airports/ermaoyun.png',url:'https://server.ermaotztz3.homes/#/?code=Vf45aB7S',price:'￥20.00/月',traffic:'130GB',device:'不限设备 · 全节点 1×',verified:true,summary:'白猫套餐月付 20 元，含 130GB 高速流量、60+ 节点和不限设备连接；页面标注 IEPL 专线与流媒体解锁。'},
{name:'光速云',tag:'套餐已核验',logo:'assets/airports/guangsuyun.png',url:'https://sjds8ds.guangsut.sbs/#/?code=RrfZcKT5',price:'￥23.00/月',traffic:'148GB',device:'不限设备 · 全节点 1×',verified:true,summary:'极速版月付 23 元、148GB；流光版月付 34 元、238GB。页面标注全球 IPLC、单节点最高 2.5Gbps。'},
{name:'边缘节点',tag:'主推套餐',logo:'assets/airports/bianyuan.png',url:'https://bcbhk40y.ztymforedge.lol/#/?code=HgD5cJEh',price:'￥22.00/月',traffic:'120GB',device:'不限设备 · 全节点 1×',verified:true,summary:'标准套餐月付 22 元、120GB；另有 98 元年付 45GB/月与 100 元一次性永久 100GB 流量包。'},
{name:'Flybit',tag:'公开资料核验',logo:'assets/airports/new/flybit.png',url:'https://www.fastfastfast.buzz/#/register?code=tuAiVVbP',price:'￥12.80/月',traffic:'150GB',device:'1 台设备',verified:true,evidence:'Bing 公开套餐页',summary:'公开套餐页显示轻量套餐 12.8 元/月、150GB；另有 16.8 元 300GB 与 28.8 元 1000GB 档。'},
{name:'龙猫云',tag:'公开资料核验',logo:'assets/airports/new/longmaoyun.svg',url:'https://inv06.lmaff01.cc/register?aff=PIB8x7dJ',price:'￥15.00/月',traffic:'100GB',device:'多设备 · 专线资料',verified:true,evidence:'Bing 多来源交叉核对',summary:'公开资料较一致的常规档为 15 元/月 100GB，另有 30 元 200GB 与 60 元 400GB；付款前仍需核对后台实时价格。'},
{name:'青云梯',tag:'公开资料核验',logo:'assets/airports/new/qingyunti.svg',url:'https://inv02.qytaff.cc/register?aff=WkyKiasW',price:'￥25.00/月',traffic:'150GB',device:'不限设备 · 全节点 1×',verified:true,evidence:'Bing 多来源交叉核对',summary:'VIP1 公开价 25 元/月、150GB；VIP2 为 45 元 300GB，年付小包 96 元、每月 60GB。资料称为 IPLC 专线。'},
{name:'大哥云',tag:'公开资料核验',logo:'assets/airports/new/dageyun.png',url:'https://a03.dgy02.com/#/register?code=vjFaxWEI',price:'￥19.90/月',traffic:'100GB',device:'500Mbps · 设备数待结算页',verified:true,evidence:'Bing 近期套餐记录',summary:'近期公开记录显示单月 A 为 19.9 元、100GB；另有 29 元 150GB、69 元季付 200GB/月与 88 元小流量年付。'},
{name:'泡芙云',tag:'公开资料核验',logo:'assets/airports/new/paofuyun.png',url:'https://www.paofu.cloud/auth/register?code=qC0O',price:'￥12.00/月',traffic:'50GB',device:'2 台 · 200Mbps',verified:true,evidence:'Bing 公开套餐记录',summary:'轻量泡芙公开记录为 12 元/月、50GB、2 台设备、200Mbps；小泡芙 22 元 200GB，大泡芙 32 元 300GB。'},
{name:'星岛梦',tag:'公开资料核验',logo:'assets/airports/new/xingdaomeng.png',url:'https://rweqr.xdmttt4.click/#/?code=lSVhHFnY',price:'￥25.00/月',traffic:'150GB',device:'不限设备 · 1×倍率资料',verified:true,evidence:'Bing 2026-08 套餐记录',summary:'较新的公开记录显示月付 25 元 150GB、50 元 300GB、70 元 500GB，并有 96 元年付 60GB/月；入口与价格需付款前复核。'},
{name:'网际快车',tag:'公开资料核验',logo:'assets/airports/new/wangjikuai.svg',url:'https://johhhu.xn--66tw07h.com',price:'￥24.00/次',traffic:'100GB 不限时',device:'不限设备资料',verified:true,evidence:'Bing 2026-07 套餐记录',summary:'标准不限时包公开价 24 元、100GB；另有 6.8 元 20GB、44 元 200GB，以及 28 元/30 天的每日 60GB 日享包。'},
];

