const deviceTitle=[...document.querySelectorAll('.content-title')].find(el=>el.textContent.includes('按设备查看'));
if(deviceTitle){
  const oldGrid=deviceTitle.nextElementSibling;if(oldGrid?.classList.contains('content-grid'))oldGrid.remove();
  const nav=document.createElement('section');nav.className='device-nav';nav.innerHTML=`
    <a href="#guide-windows"><b>01</b><strong>Windows</strong><span>Clash Party</span></a>
    <a href="#guide-macos"><b>02</b><strong>macOS</strong><span>Clash Party</span></a>
    <a href="#guide-ios"><b>03</b><strong>iPhone / iPad</strong><span>Shadowrocket</span></a>
    <a href="#guide-android"><b>04</b><strong>Android</strong><span>兼容客户端</span></a>
    <a href="#guide-linux"><b>05</b><strong>Linux</strong><span>Clash Party</span></a>`;
  deviceTitle.after(nav);
  const guides=document.createElement('section');guides.className='system-guides';guides.innerHTML=`
  <article id="guide-windows" class="system-guide"><header><span>01 / WINDOWS</span><h2>Windows 使用教程</h2><p>适用于 Windows 10/11，推荐 Clash Party x64 安装版。</p></header><ol><li><b>下载安装</b><p>进入官方 Releases，下载文件名包含 Windows、x64 的安装包。完成安装后启动应用。</p></li><li><b>复制订阅</b><p>登录机场后台，在仪表盘找到“一键订阅”或“订阅地址”，复制完整链接。</p></li><li><b>导入配置</b><p>在 Clash Party 的订阅或配置页面选择“从 URL 导入”，粘贴链接并更新。</p></li><li><b>选择节点</b><p>打开代理组，先选择香港、日本或新加坡节点。延迟数字只用于初筛，仍需实际打开网页验证。</p></li><li><b>开启代理</b><p>开启系统代理；需要所有程序都经过代理时再使用 TUN 模式，并允许系统防火墙权限。</p></li><li><b>确认连接</b><p>打开常用网站测试。无法访问时先更新订阅、切换节点，再检查其他代理软件是否冲突。</p></li></ol></article>
  <article id="guide-macos" class="system-guide"><header><span>02 / MACOS</span><h2>macOS 使用教程</h2><p>先确认 Mac 使用 Apple 芯片还是 Intel 芯片，再选择对应安装包。</p></header><ol><li><b>确认芯片</b><p>点击苹果菜单 → 关于本机。显示 M1/M2/M3/M4 时选择 arm64；显示 Intel 时选择 x64。</p></li><li><b>安装客户端</b><p>从 Clash Party 官方 Releases 下载 macOS 对应版本，将应用拖入“应用程序”。</p></li><li><b>首次授权</b><p>首次开启系统代理或 TUN 模式时，macOS 会要求输入系统密码并允许网络扩展。</p></li><li><b>导入订阅</b><p>复制机场订阅链接，在客户端中选择从 URL 导入，然后刷新配置。</p></li><li><b>选择模式</b><p>日常使用选择规则模式；只有排查特定网站问题时再临时使用全局模式。</p></li><li><b>退出前恢复</b><p>退出客户端前先关闭系统代理，避免下次开机出现浏览器无法联网。</p></li></ol></article>
  <article id="guide-ios" class="system-guide"><header><span>03 / IOS & IPADOS</span><h2>iPhone / iPad 使用教程</h2><p>使用 Shadowrocket 小火箭，通过 App Store 安装。</p></header><ol><li><b>安装应用</b><p>从本页 App Store 官方入口获取 Shadowrocket。不同地区商店的可用情况可能不同。</p></li><li><b>获取订阅</b><p>用 Safari 登录机场后台，复制订阅链接。不要将链接发送给其他人。</p></li><li><b>导入订阅</b><p>打开小火箭，点击右上角添加按钮，选择 Subscribe/订阅，粘贴 URL 并保存。</p></li><li><b>更新节点</b><p>在订阅项目上刷新，确认节点列表出现。先选距离较近的节点。</p></li><li><b>允许 VPN</b><p>打开顶部连接开关，系统会弹出添加 VPN 配置提示；确认后通过面容、指纹或密码授权。</p></li><li><b>移动网络设置</b><p>Wi-Fi 正常但蜂窝网络不通时，检查小火箭是否允许使用蜂窝数据，并重新连接。</p></li></ol></article>
  <article id="guide-android" class="system-guide"><header><span>04 / ANDROID</span><h2>Android 使用教程</h2><p>Android 客户端较多，优先使用机场明确支持并链接到官方项目的版本。</p></header><ol><li><b>确认客户端</b><p>在机场使用文档中确认推荐客户端和支持协议，不要从群文件或陌生网盘下载修改版。</p></li><li><b>安装应用</b><p>从官方项目发布页下载与手机架构兼容的 APK。系统提示未知来源时先核对文件来源。</p></li><li><b>导入订阅</b><p>复制订阅 URL，在配置页面选择从链接导入或新建配置，并更新节点。</p></li><li><b>开启 VPN</b><p>点击连接并允许创建 VPN。状态栏出现钥匙或 VPN 图标表示系统通道已建立。</p></li><li><b>后台保活</b><p>在电池设置中允许客户端后台运行，关闭针对该应用的省电限制，避免锁屏后断开。</p></li><li><b>分应用代理</b><p>只有明确需要时开启分应用代理；出现部分应用无法联网时先恢复为全部应用。</p></li></ol></article>
  <article id="guide-linux" class="system-guide"><header><span>05 / LINUX</span><h2>Linux 使用教程</h2><p>适合桌面 Linux 用户，建议熟悉软件包格式和系统代理设置后使用。</p></header><ol><li><b>选择安装包</b><p>在 Clash Party Releases 中按发行版选择 AppImage、deb 或 rpm，并确认 x64/arm64 架构。</p></li><li><b>赋予权限</b><p>AppImage 需要添加可执行权限；deb/rpm 使用对应包管理器安装。</p></li><li><b>导入订阅</b><p>启动客户端后从 URL 导入订阅并更新配置，选择可用节点。</p></li><li><b>桌面代理</b><p>GNOME/KDE 可使用系统代理；需要透明代理时再配置 TUN，并按提示授予权限。</p></li><li><b>检查 DNS</b><p>连接后无法解析域名时，检查 systemd-resolved、NetworkManager 与客户端 DNS 设置是否冲突。</p></li><li><b>查看日志</b><p>启动失败或节点错误时查看客户端日志，确认端口占用、权限和配置文件报错。</p></li></ol></article>`;
  const trouble=document.querySelector('.troubleshoot');if(trouble)trouble.before(guides);
}
