(function(){
 const data=typeof AIRPORT_RANKING==='undefined'?[]:AIRPORT_RANKING;if(!data.length)return;
 const assessments=[
  ['综合优选','商务优选','高清畅看','高峰优选','假期优选'],['影音友好','灵活办公','流畅播放','高峰稳健','长假适配'],['多区适配','跨区优选','多场景畅看','线路灵活','出行友好'],['大流量影音','团队适配','追剧优选','多设备友好','家庭优选'],['高流量适配','办公优选','持续播放','重度使用','长期友好'],['日常实用','入门友好','影音均衡','高峰适配','备用优选'],['影音良好','办公良好','播放良好','高峰良好','假期良好'],['多区良好','办公适配','高清视频','高峰尚稳','假期适配'],['套餐灵活','备用适配','视频良好','高峰尚稳','假期可用'],['日常良好','办公适配','播放良好','高峰适配','假期适配'],['影音适配','日常办公','视频稳定','高峰可用','假期可用'],['线路均衡','办公适配','视频良好','高峰适配','出行适配'],['日常适配','轻量办公','视频适配','高峰可用','假期可用'],['轻量实用','基础办公','日常视频','高峰可用','备用适配'],['影音适配','日常办公','视频良好','高峰适配','假期可用'],['备用灵活','轻量办公','按量观看','高峰可用','出行备用']
 ];
 const overall=i=>i<3?'综合优选':i<6?'表现均衡':i<9?'综合良好':i<12?'日常适配':'基础实用';
 const brand=a=>a.logo?`<img src="${a.logo}" alt="${a.name} Logo">`:`<div class="review-monogram">${a.monogram||a.name}</div>`;
 if(location.pathname.endsWith('recommend.html')){const cards=[...document.querySelectorAll('.airport-card')];cards.forEach((card,i)=>{if(i<9||!data[i])return;const a=data[i];card.classList.remove('airport-card-new');const logo=card.querySelector('.airport-logo');if(logo)logo.innerHTML=brand(a);const tag=card.querySelector('.discount-pill');if(tag)tag.textContent=a.tag;const summary=card.querySelector('.airport-body>p');if(summary)summary.textContent=a.summary;const label=card.querySelector('.reason-label');if(label)label.textContent='公开资料核验';const reasons=card.querySelector('.airport-reasons');if(reasons)reasons.innerHTML=`<li>公开入门价：${a.price}</li><li>公开套餐流量：${a.traffic}；${a.device}</li><li>综合定位：${overall(i)}，适合先从短周期套餐开始体验</li>`;const status=card.querySelector('.listing-status');if(status)status.outerHTML=`<div class="price-box"><div class="price-head"><span>公开入门套餐</span><strong>${a.price}</strong></div><div class="price-list"><div>套餐流量<strong>${a.traffic}</strong></div><div>设备/倍率<strong>${a.device}</strong></div><div>综合定位<strong>${overall(i)}</strong></div><div>场景表现<strong>${assessments[i][2]}</strong></div></div></div>`;const link=card.querySelector('.airport-link');if(link){link.href=a.url;link.innerHTML=`查看${a.name}套餐 <span>↗</span>`}});const disclosure=document.querySelector('.disclosure');if(disclosure)disclosure.textContent='价格与流量来自服务商页面、用户截图或 Bing 可检索公开资料；场景标签是依据套餐结构、线路资料与榜单权重形成的编辑综合评估。活动与实际结算价可能调整，请以服务商页面为准。本页包含推广链接。'}
 if(location.pathname.endsWith('reviews.html')){const grid=document.querySelector('.review-cards');if(grid)grid.innerHTML=data.map((a,i)=>`<article class="review-detail"><div class="review-brand">${brand(a)}<div><span>${String(i+1).padStart(2,'0')} / ${a.tag}</span><h3>${a.name}</h3></div></div><p>${a.summary}</p><div class="verified-data"><b>${a.price}<small>公开入门价</small></b><b>${a.traffic}<small>公开流量</small></b><b>${a.device}<small>设备/倍率</small></b><b>${overall(i)}<small>综合评估</small></b></div><ul><li>排名：当前综合推荐榜第 ${i+1} 名</li><li>场景：${assessments[i].join(' · ')}</li><li>结论：第 7 名以后与前六名保持小幅梯度，更适合作为按预算和场景选择的备选</li></ul><a href="${a.url}" target="_blank" rel="sponsored nofollow noopener">查看${a.name}页面 ↗</a></article>`).join('');const meta=document.querySelector('.page-meta');if(meta&&meta.children[0])meta.children[0].textContent=`${data.length} 家机场`;const title=[...document.querySelectorAll('.content-title h2')].find(e=>e.textContent.includes('机场逐项测评'));if(title)title.textContent=`${data.length} 家机场逐项测评`}
 if(location.pathname.endsWith('compare.html')){const body=document.querySelector('.compare-table tbody');if(body)body.innerHTML=data.map((a,i)=>`<tr><td><b>${i+1}</b> ${a.name}</td><td>${a.price}</td><td>${a.traffic}</td><td>${a.device}</td>${assessments[i].map(v=>`<td>${v}</td>`).join('')}</tr>`).join('');const meta=document.querySelector('.page-meta');if(meta&&meta.children[0])meta.children[0].textContent=`${data.length} 家机场`;const note=document.querySelector('.compare-note p');if(note)note.innerHTML='<b>场景标签</b>依据公开套餐、线路资料、价格流量和当前榜单权重进行统一编辑评估。前六名强调综合表现，第 7 名以后保持小幅梯度，方便按预算和用途选择。'}
})();
